// Presentation-only catalog. Translation never changes scenario keys, names or saves.
const pairs:Record<string,string>={
 'Kleine Wege. Großes Leben.':'Small paths. A bigger life.','Drei Ecken, ein guter Morgen':'Three corners, one good morning','Fiktives Testviertel · Prototyp 0.1':'Fictional test district · Prototype 0.1',
 'So geht’s':'How to play','Speichern':'Save','DEIN VIERTEL':'YOUR DISTRICT','Eine kleine Idee':'One small idea','verändert den Morgen.':'changes the morning.','Folge einem Weg.':'Follow a journey.','Verändere, was dich stört.':'Change what gets in the way.',
 'Verbinden':'Connect','Umverteilen':'Rebalance','Beleben':'Bring to life','Öffne einzelne Anschlüsse. Kombiniere die Wege zu deinem eigenen Entwurf.':'Open individual connections. Combine paths into your own design.',
 'Schuldurchgang':'School passage','Westlicher Grünweg':'Western green path','Schulanschluss':'School connection','Östlicher Grünweg':'Eastern green path','Offen':'Open','Aktiv':'Active',
 'Wohnhof':'Home courtyard','Schule':'School','Grünort':'Green space','Ostkreuz':'East junction','Atelierhof':'Studio courtyard','Ausfahrt':'Exit','WOHNHOF':'HOME COURTYARD','SCHULE':'SCHOOL','ATELIERHOF':'STUDIO COURTYARD','AUSFAHRT':'EXIT','DEIN GRÜNORT':'YOUR GREEN SPACE',
 'Baubudget':'Building budget','Unbegrenzt':'Unlimited','Frei gestalten · ohne Budget':'Free design · no budget','Zurück':'Undo','Verwerfen':'Discard',
 'Die Querstraße gehört allen. Wie verteilst du ihren begrenzten Raum?':'The cross street is shared. How will you use its limited space?','Gemischt':'Mixed use','Auto, Rad und Fuß · breite Autozufahrt':'Cars, bikes and walking · wide car access','Mehr Raum fürs Rad':'More room for bikes','Schneller radeln · engere Autozufahrt':'Faster cycling · narrower car access','Autofrei':'Car-free','Fuß und Rad · Autos nehmen den Südweg':'Walking and cycling · cars use the southern route',
 'Gestalte deinen Ort. Ein angeschlossener Eingang und freie Zeit bringen Menschen hierher.':'Make this place your own. A connected entrance and spare time bring people here.','Freie Fläche':'Open plot','Noch kein Aufenthaltsort':'Not a place to visit yet','Kleiner Garten':'Small garden','8 Plätze · 25 Punkte':'8 spaces · 25 points','Grüner Platz':'Green square','14 Plätze · 35 Punkte':'14 spaces · 35 points','Eingang':'Entrance','West · zum Wohnhof':'West · towards home','Ost · zum Atelierhof':'East · towards the studios','Eingang versetzen: 5 Punkte bei gebautem Ort.':'Moving an entrance: 5 points for a built place.',
 'DREI PERSPEKTIVEN':'THREE PERSPECTIVES','Bewohner':'Residents','Noch zu Hause':'Still at home','Unterwegs':'On the way','Wartet am Engpass':'Waiting at the bottleneck','Macht eine Pause':'Taking a break','Am Tagesziel':'At the destination','Ziel nicht erreichbar':'Destination unreachable',
 'Schulweg zu Fuß · Ankunft bis 07:39':'Walking to school · arrive by 07:39','Mit dem Rad ins Atelier · Pause 08:05–08:18:30':'Cycling to the studio · break 08:05–08:18:30','Externes Arbeitsziel · Auto für diese Reise erforderlich':'Work outside the district · car required for this trip','Reise im Entwurf':'Journey in this design','Vorher':'Before','Wartezeit':'Waiting time','Nicht erreichbar':'Unreachable',
 'Kürzester erlaubter Weg für Fußwege. Tatsächliche Wartezeiten werden mitgerechnet.':'Shortest permitted walking route. Actual waiting times are included.','Kürzester erlaubter Weg für das Fahrrad. Tatsächliche Wartezeiten werden mitgerechnet.':'Shortest permitted cycling route. Actual waiting times are included.','Kürzester erlaubter Weg für das Auto. Tatsächliche Wartezeiten werden mitgerechnet.':'Shortest permitted driving route. Actual waiting times are included.','Keine durchgehend erlaubte Verbindung.':'No complete permitted route.',
 'Eine Pause im Grünort ist möglich.':'A break in the green space is possible.','Noch keine Pause im Grünort.':'No visit to the green space yet.','Hinweg, 90 Sekunden Pause und Rückweg passen; ein Platz ist frei.':'The walk there, a 90-second break and the return fit; a space is available.','Noch kein gestalteter Aufenthaltsort.':'No designed place to visit yet.','Der gewählte Platzeingang ist nicht angeschlossen.':'The selected entrance is not connected.','Das Tagesziel wurde vor der Pause nicht erreicht.':'The destination was not reached before the break.','Kein nutzbarer Hin- und Rückweg.':'No usable outward and return route.','Hinweg, 90 Sekunden Pause und Rückweg passen nicht ins Zeitfenster.':'The walks and a 90-second break do not fit the available time.','Der Ort ist in diesem Zeitfenster belegt.':'The place is full during this time window.','Kein freies Zeitfenster.':'No spare time window.',
 'Entwurf':'Design','Ausgangsmorgen':'Baseline morning','Zur Person':'Find this person','DEIN ENTWURF':'YOUR DESIGN','Ein Morgen voller Möglichkeiten.':'A morning full of possibilities.','Eine Idee nimmt Gestalt an.':'An idea is taking shape.','Morgen abspielen':'Play the morning','Pause':'Pause','Ein guter Morgen':'A good morning','Zeit im Morgen':'Time of morning','Denselben Morgen erneut abspielen':'Replay the same morning','Morgen vergleichen':'Compare mornings','Übernehmen':'Keep this design',
 'DENSELBEN MORGEN VERGLEICHEN':'COMPARE THE SAME MORNING','Was deine Idee bewirkt.':'What your idea changes.','Vergleich schließen':'Close comparison','Schließen':'Close','Dein Ort wird benutzt.':'Your place is being used.','Was könnte den Morgen verändern?':'What could change the morning?','Untersuche Maras Umweg oder verbinde den Eingang deines Grünorts.':'Explore Mara’s detour or connect the entrance to your green space.',
 'Ziehen: drehen · Rechts ziehen: verschieben · Scrollen: zoomen':'Drag: rotate · Right drag: pan · Scroll: zoom','Impressum':'Legal notice','Datenschutz':'Privacy','AGB / Nutzung':'Terms of use','Spielstand':'Saved game',
 'Wähle Mara. Welchen Weg würdest du ihr öffnen?':'Choose Mara. Which route would you open for her?','Entwurf geändert. Derselbe Morgen steht zum Ausprobieren bereit.':'Design changed. The same morning is ready to try.','Der Entwurf wurde verworfen. Das Budget bleibt erhalten.':'Design discarded. Your budget is unchanged.','Dein Viertel ist übernommen. Es ist jetzt der neue Ausgangsmorgen.':'Your district is saved as the new baseline morning.','Spielstand in diesem Browser gespeichert.':'Game saved in this browser.','Speichern ist blockiert. Über „Spielstand“ kannst du eine Datei exportieren.':'Browser saving is blocked. Use Saved game to export a file.','Spielstand geladen.':'Saved game loaded.','Das Baubudget reicht für diesen Entwurf nicht.':'This design exceeds your building budget.','Ungültiger Entwurf.':'Invalid design.',
 'Dein Spielstand':'Your saved game','Nur bei „Speichern“ wird dein Spielstand lokal in diesem Browser abgelegt. Keine Konten und keine Übertragung deines Spielstands. Für Seitenabrufe gelten die zentralen Datenschutzhinweise. Ein Datei-Export sichert deinen Stand unabhängig vom Browser.':'Your game is stored locally only when you click Save. No account and no upload of your game. The central privacy notice applies to page requests. A file export backs up your progress independently of this browser.',
 'Datei exportieren':'Export file','Datei laden':'Load file','Gespeicherten Stand laden':'Load saved game','Browserspeicher löschen':'Clear browser save','Neues Testviertel':'New test district','Noch kein gespeicherter Stand.':'No saved game yet.','Browserspeicher nicht zugänglich.':'Browser storage is unavailable.','Die Spielstanddatei ist zu groß.':'The save file is too large.','Gespeicherte Browserkopie gelöscht. Die laufende Sitzung bleibt erhalten.':'Browser save deleted. The current session is unchanged.','Neues Testviertel?':'Start a new test district?','Die laufende Sitzung wird ersetzt. Eine bereits gespeicherte Browserkopie bleibt erhalten.':'This replaces the current session. An existing browser save is preserved.','Neu beginnen':'Start again','Zurück ins Viertel':'Back to the district',
 'WILLKOMMEN IM VIERTEL':'WELCOME TO THE DISTRICT','Folge deiner nächsten Idee.':'Follow your next idea.','Wähle Mara und sieh ihren Schulweg an. Grün zeigt deinen Entwurf, Sand den Ausgangsmorgen.':'Choose Mara to see her walk to school. Green shows your design; sand shows the baseline.','Öffne einen einzelnen Anschluss unter':'Open an individual connection under',' . Wege lassen sich kombinieren.':'. Paths can be combined.','. Wege lassen sich kombinieren.':'. Paths can be combined.','Starte denselben Morgen. 1× entspricht einer Spielsekunde pro realer Sekunde; 20× beschleunigt ihn.':'Play the same morning. 1× is one game second per real second; 20× speeds it up.','Vergleiche die Folgen für Mara, Cem und Ruth. Übernehmen macht deinen Entwurf zum neuen Ausgangszustand.':'Compare the effects on Mara, Cem and Ruth. Keep this design makes it your new baseline.','Gestalte einen Garten oder Platz. Cem braucht einen angeschlossenen Eingang und genügend Zeit für Hinweg, Pause und Rückweg.':'Design a garden or square. Cem needs a connected entrance and enough time to get there, stay and return.','Du darfst jederzeit frei bauen. Leertaste pausiert, Escape schließt Dialoge. Das Viertel ist erfunden; reale Ehrenfeld-Geometrie folgt in einer späteren Stufe.':'You can build freely at any time. Space pauses; Escape closes dialogs. This district is fictional; real Ehrenfeld geometry is planned for a later stage.',
 'Spielstand lokal speichern':'Save locally in this browser','Zur MINTERRA-Website':'Back to the MINTERRA website','Dein Viertel erwacht.':'Your district is waking up.','Wege und Tagespläne werden vorbereitet.':'Preparing routes and daily plans.',
 'Die 3D-Ansicht konnte nicht starten.':'The 3D view could not start.','Bitte Hardwarebeschleunigung aktivieren und einen aktuellen Browser verwenden.':'Please enable hardware acceleration and use a current browser.','Drehbare Miniaturstadt. Bauwerkzeuge und Bewohner sind auch über die Schaltflächen erreichbar.':'Rotatable miniature city. Building tools and residents are also accessible through buttons.'
};
function translate(s:string){const stripped=s.trim();if(pairs[stripped])return s.replace(stripped,pairs[stripped]);
 if(/^\d+ Punkte$/.test(stripped))return stripped.replace('Punkte','points');
 if(/^\d+,\d Min\.$/.test(stripped))return stripped.replace(',','.').replace('Min.','min');
 if(stripped.includes(' – '))return stripped.split(' – ').map(t=>pairs[t]||t).join(' – ');
 return s.replace(/kommt früher an\./g,'arrives earlier.').replace(/braucht länger\./g,'takes longer.').replace(/weniger unterwegs als im Ausgangsmorgen\./g,'less travel time than in the baseline morning.').replace(/zusätzlich\. Prüfe die Autozufahrt\./g,'extra. Check the car access.').replace(/berechnete Besuche mit Hin- und Rückweg\./g,'calculated visits including outward and return journeys.').replace(/Pünktlich:/g,'On time:').replace(/ von /g,' of ').replace(/Nicht erreichbar:/g,'Unreachable:').replace(/Besuche:/g,'Visits:').replace(/Min\./g,'min');
}
export function languageControl(){let language:'de'|'en'='de';const textOriginal=new WeakMap<Node,string>(),attrOriginal=new WeakMap<Element,Record<string,string>>(),attrOutput=new WeakMap<Element,Record<string,string>>();
 const button=document.createElement('button');button.id='language';button.textContent='DE';button.setAttribute('aria-label','Switch to English');document.querySelector('.header-actions')!.prepend(button);
 const obs=new MutationObserver(()=>{if(language==='en')apply();});
 const watch=()=>obs.observe(document.getElementById('app')!,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label']});
 function apply(){obs.disconnect();const walker=document.createTreeWalker(document.getElementById('app')!,NodeFilter.SHOW_TEXT);let node:Node|null;while(node=walker.nextNode()){if(node.parentElement?.closest('script,style,#language'))continue;if(!textOriginal.has(node))textOriginal.set(node,node.textContent||'');const original=textOriginal.get(node)!;const output=language==='en'?translate(original):original;if(node.textContent!==output)node.textContent=output;}
 document.querySelectorAll('#app [aria-label],#app [title]').forEach(el=>{if(el===button)return;let originals=attrOriginal.get(el);const last=attrOutput.get(el)||{};if(!originals){originals={};for(const a of ['title','aria-label'])if(el.hasAttribute(a))originals[a]=el.getAttribute(a)!;attrOriginal.set(el,originals);}for(const a of Object.keys(originals)){const current=el.getAttribute(a)!;if(last[a]!==undefined&&current!==last[a])originals[a]=current;const output=language==='en'?translate(originals[a]):originals[a];if(current!==output)el.setAttribute(a,output);last[a]=output;}attrOutput.set(el,last);});document.documentElement.lang=language;button.textContent=language.toUpperCase();button.setAttribute('aria-label',language==='de'?'Switch to English':'Auf Deutsch wechseln');watch();}
 button.onclick=()=>{language=language==='de'?'en':'de';apply();};watch();
}
