import './style.css';
import {languageControl} from './i18n';
import {World} from './world';
import {connections,changeCost,clock,END,point,position,type Layout,type Result} from './simulation';
import {fresh,parseSave,edit,commit,type Save} from './state';
const icons:Record<string,string>={play:'M8 5v14l11-7z',pause:'M7 5h3v14H7z M14 5h3v14h-3z',link:'M3 17 9 11l4 4 8-9 M15 6h6v6',road:'M8 3 4 21 M16 3l4 18 M12 4v3m0 4v3m0 4v3',leaf:'M20 4C9 2 3 8 6 15c8 5 14-2 14-11ZM4 21 15 10',undo:'M8 5 3 10l5 5 M3 10h11a6 6 0 0 1 0 12',reset:'M4 10a8 8 0 1 1 0 6 M4 4v6h6',save:'M5 3h12l4 4v14H3V3h2Zm2 0v7h10V3M7 21v-8h10v8',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Zm7 0a3 3 0 1 0 6 0 3 3 0 0 0-6 0',sun:'M12 3v2m0 14v2M3 12h2m14 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0'};
const icon=(id:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[id]}"/></svg>`;
document.querySelector('#app')!.innerHTML=`
 <canvas id="world" aria-label="Drehbare Miniaturstadt. Bauwerkzeuge und Bewohner sind auch über die Schaltflächen erreichbar." tabindex="0"></canvas><div id="world-labels"></div>
 <header><a class="brand" href="https://jonaschlegelmilch.de/minterra/" title="Zur MINTERRA-Website"><img src="./icon.svg" alt=""><div><strong>MINTERRA</strong><span>Kleine Wege. Großes Leben.</span></div></a><div class="location"><span class="live-dot"></span> Drei Ecken, ein guter Morgen <small>Fiktives Testviertel · Prototyp 0.1</small></div><div class="header-actions"><button id="help">So geht’s</button><button id="save" title="Spielstand lokal speichern">${icon('save')}<span>Speichern</span></button></div></header>
 <aside class="tools panel"><div class="eyebrow">DEIN VIERTEL</div><h1>Eine kleine Idee<br>verändert den Morgen.</h1><p class="intro">Folge einem Weg.<br>Verändere, was dich stört.</p><div class="tool-tabs"><button data-tool="connect" class="active">${icon('link')}Verbinden</button><button data-tool="street">${icon('road')}Umverteilen</button><button data-tool="park">${icon('leaf')}Beleben</button></div><div id="tool-content"></div><div class="budget"><span>Baubudget</span><strong id="budget"></strong></div><label class="check"><input id="unlimited" type="checkbox"> Frei gestalten · ohne Budget</label><div class="edit-actions"><button id="undo">${icon('undo')}Zurück</button><button id="discard">Verwerfen</button></div></aside>
 <aside class="people panel"><div class="eyebrow">DREI PERSPEKTIVEN</div><nav aria-label="Bewohner" class="residents"><button data-person="0" class="active"><i class="avatar mara">M</i>Mara</button><button data-person="1"><i class="avatar cem">C</i>Cem</button><button data-person="2"><i class="avatar ruth">R</i>Ruth</button></nav><div id="person-detail"></div><div class="route-key"><span><i></i>Entwurf</span><span><i></i>Ausgangsmorgen</span></div><button id="focus" class="wide">${icon('eye')}Zur Person</button></aside>
 <div class="world-caption"><span class="caption-rule"></span><span>DEIN ENTWURF<br><small id="world-status">Ein Morgen voller Möglichkeiten.</small></span></div>
 <section id="observations" class="panel observations" hidden></section>
 <section class="timeline panel"><button id="play" class="play" title="Morgen abspielen">${icon('play')}</button><div class="time"><strong id="clock">07:30</strong><span>Ein guter Morgen</span></div><input id="scrub" type="range" min="0" max="5400" step="1" value="0" aria-label="Zeit im Morgen"><div class="speeds"><button data-speed="1">1×</button><button data-speed="5">5×</button><button data-speed="20" class="active">20×</button></div><button id="restart" title="Denselben Morgen erneut abspielen">${icon('reset')}</button><button id="compare" class="primary">Morgen vergleichen</button><button id="accept" disabled>Übernehmen</button></section>
 <footer><a href="https://www.linkedin.com/in/jonaschlegelmilch/" target="_blank" rel="noreferrer">Created by Jona Fynn Schlegelmilch</a><span>Ziehen: drehen · Rechts ziehen: verschieben · Scrollen: zoomen</span><nav><span id="legal-slot"></span><button id="data">Spielstand</button></nav></footer>
 <div id="toast" role="status" aria-live="polite"></div><div id="loading" class="loading"><div class="loader"></div><strong>Dein Viertel erwacht.</strong><span>Wege und Tagespläne werden vorbereitet.</span></div>
 <dialog id="dialog"><div id="dialog-content"></div><button id="close-dialog" class="primary">Zurück ins Viertel</button></dialog>`;
document.getElementById('legal-slot')?.replaceWith(document.querySelector('.jano-legal-links')!);
languageControl();
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let state:Save=fresh(),tool='connect',speed=20,playing=false,baseline:Result,result:Result,busy=true,compared=false;
const worker=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});let request=0;const pending=new Map<number,{resolve:(r:Result)=>void;reject:(e:Error)=>void}>();
worker.onmessage=e=>{const p=pending.get(e.data.id);if(!p)return;pending.delete(e.data.id);e.data.error?p.reject(Error(e.data.error)):p.resolve(e.data.result);};
worker.onerror=()=>{for(const p of pending.values())p.reject(Error('Die Simulation konnte nicht gestartet werden.'));pending.clear();};
function compute(layout:Layout){return new Promise<Result>((resolve,reject)=>{const id=++request;pending.set(id,{resolve,reject});worker.postMessage({id,layout,count:state.count});});}
let world:World;try{world=new World($<HTMLCanvasElement>('world'),$('world-labels'));}catch(e){$('loading').innerHTML='<strong>Die 3D-Ansicht konnte nicht starten.</strong><p>Bitte Hardwarebeschleunigung aktivieren und einen aktuellen Browser verwenden.</p>';throw e;}
function toast(text:string){$('toast').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),4500);}
function money(n:number){return `${n} Punkte`;}
function seconds(n:number){return `${(n/60).toFixed(1).replace('.',',')} Min.`;}
function details(){if(!result)return;const j=result.journeys[state.selected],b=baseline.journeys[state.selected],p=position(j,state.time);const labels:Record<string,string>={home:'Noch zu Hause',move:'Unterwegs',wait:'Wartet am Engpass',stay:'Macht eine Pause',arrived:'Am Tagesziel',unreachable:'Ziel nicht erreichbar'};
 $('person-detail').innerHTML=`<h2>${j.person.name}<span>${labels[p.kind]||p.kind}</span></h2><p>${j.person.bio}</p><div class="journey"><span>${point(j.person.home).name}</span><span class="journey-line"></span><strong>${point(j.person.goal).name}</strong></div><dl><div><dt>Reise im Entwurf</dt><dd>${j.arrival===null?'Nicht erreichbar':seconds(j.arrival-j.person.depart)}</dd></div><div><dt>Vorher</dt><dd>${b.arrival===null?'Nicht erreichbar':seconds(b.arrival-b.person.depart)}</dd></div><div><dt>Wartezeit</dt><dd>${seconds(j.wait)}</dd></div></dl><p class="reason">${j.route?'Kürzester erlaubter Weg für '+({walk:'Fußwege',bike:'das Fahrrad',car:'das Auto'}[j.person.mode])+'. Tatsächliche Wartezeiten werden mitgerechnet.':'Keine durchgehend erlaubte Verbindung.'}</p>${state.selected===1?`<p class="visit"><strong>${j.visit?'Eine Pause im Grünort ist möglich.':'Noch keine Pause im Grünort.'}</strong>${j.visitReason}</p>`:''}`;
}
function controls(){const l=state.draft;$('budget').textContent=l.unlimited?'Unbegrenzt':`${state.remaining-changeCost(state.base,l)} / ${state.remaining}`;$<HTMLInputElement>('unlimited').checked=l.unlimited;$<HTMLButtonElement>('undo').disabled=!state.history.length||busy;$<HTMLButtonElement>('accept').disabled=busy||!compared;$('world-status').textContent=JSON.stringify(l)===JSON.stringify(state.base)?'Ein Morgen voller Möglichkeiten.':'Eine Idee nimmt Gestalt an.';
 document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===tool);b.setAttribute('aria-pressed',String(b.dataset.tool===tool));});
 if(tool==='connect')$('tool-content').innerHTML=`<p class="tool-note">Öffne einzelne Anschlüsse. Kombiniere die Wege zu deinem eigenen Entwurf.</p>${connections.map(c=>`<button class="build-option ${l.links.includes(c.id)?'built':''}" data-link="${c.id}" aria-pressed="${l.links.includes(c.id)}"><span>${c.name}<small>${point(c.a).name} – ${point(c.b).name}</small></span><b>${l.links.includes(c.id)?'Offen':money(c.cost)}</b></button>`).join('')}`;
 if(tool==='street')$('tool-content').innerHTML=`<p class="tool-note">Die Querstraße gehört allen. Wie verteilst du ihren begrenzten Raum?</p>${[['mixed','Gemischt','Auto, Rad und Fuß · breite Autozufahrt'],['bike','Mehr Raum fürs Rad','Schneller radeln · engere Autozufahrt'],['free','Autofrei','Fuß und Rad · Autos nehmen den Südweg']].map(([id,name,note])=>`<button class="build-option ${l.street===id?'built':''}" data-street="${id}" aria-pressed="${l.street===id}"><span>${name}<small>${note}</small></span><b>${l.street===id?'Aktiv':'35 P.'}</b></button>`).join('')}`;
 if(tool==='park')$('tool-content').innerHTML=`<p class="tool-note">Gestalte deinen Ort. Ein angeschlossener Eingang und freie Zeit bringen Menschen hierher.</p>${[['none','Freie Fläche','Noch kein Aufenthaltsort'],['garden','Kleiner Garten','8 Plätze · 25 Punkte'],['square','Grüner Platz','14 Plätze · 35 Punkte']].map(([id,name,note])=>`<button class="build-option ${l.park===id?'built':''}" data-park="${id}" aria-pressed="${l.park===id}"><span>${name}<small>${note}</small></span></button>`).join('')}<label class="field">Eingang<select id="entrance"><option value="west" ${l.entrance==='west'?'selected':''}>West · zum Wohnhof</option><option value="east" ${l.entrance==='east'?'selected':''}>Ost · zum Atelierhof</option></select></label><small>Eingang versetzen: 5 Punkte bei gebautem Ort.</small>`;
 $('tool-content').querySelectorAll<HTMLButtonElement>('[data-link]').forEach(b=>b.onclick=()=>mutate(l=>{const id=b.dataset.link!;l.links=l.links.includes(id)?l.links.filter(x=>x!==id):[...l.links,id];}));
 $('tool-content').querySelectorAll<HTMLButtonElement>('[data-street]').forEach(b=>b.onclick=()=>mutate(l=>l.street=b.dataset.street as Layout['street']));
 $('tool-content').querySelectorAll<HTMLButtonElement>('[data-park]').forEach(b=>b.onclick=()=>mutate(l=>l.park=b.dataset.park as Layout['park']));
 if($('entrance'))$('entrance').onchange=e=>mutate(l=>l.entrance=(e.target as HTMLSelectElement).value as Layout['entrance']);
}
async function refresh(baseChanged=false){busy=true;playing=false;compared=false;$('observations').hidden=true;controls();try{if(baseChanged||!baseline)baseline=await compute(state.base);result=await compute(state.draft);world.update(state.draft,result,baseline,state.selected);world.time=state.time;details();}finally{busy=false;$('loading').hidden=true;controls();}}
async function mutate(fn:(l:Layout)=>void){if(busy)return;const l=structuredClone(state.draft);fn(l);try{state=edit(state,l);await refresh();toast('Entwurf geändert. Derselbe Morgen steht zum Ausprobieren bereit.');}catch(e){controls();toast((e as Error).message);}}
document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool!;controls();});
function select(id:number){state.selected=id;document.querySelectorAll('[data-person]').forEach(b=>b.classList.toggle('active',Number((b as HTMLElement).dataset.person)===id));world.showRoute(id,baseline);details();}
document.querySelectorAll<HTMLButtonElement>('[data-person]').forEach(b=>b.onclick=()=>select(Number(b.dataset.person)));
world.onSelect=(kind,id)=>{if(busy)return;if(kind==='resident'&&Number(id)<3)select(Number(id));if(kind==='connection'){tool='connect';controls();const b=document.querySelector<HTMLButtonElement>(`[data-link="${id}"]`);b?.focus();toast('Anschluss ausgewählt. Öffne ihn links mit sichtbaren Baukosten.');}if(kind==='place'&&id==='park'){tool='park';controls();}if(kind==='edge'&&id==='main'){tool='street';controls();}};
$('focus').onclick=()=>{const p=position(result.journeys[state.selected],state.time);world.camera.setTarget(new (world.camera.target.constructor as any)(p.x,0,p.z));world.camera.radius=125;};
$('undo').onclick=async()=>{if(busy||!state.history.length)return;state.draft=state.history.pop()!;state.time=0;await refresh();};
$('discard').onclick=async()=>{if(busy)return;state.draft=structuredClone(state.base);state.history=[];state.time=0;await refresh();toast('Der Entwurf wurde verworfen. Das Budget bleibt erhalten.');};
$<HTMLInputElement>('unlimited').onchange=e=>mutate(l=>l.unlimited=(e.target as HTMLInputElement).checked);
$('play').onclick=()=>{if(busy)return;if(state.time>=END)state.time=0;playing=!playing;};
$('restart').onclick=()=>{state.time=0;playing=true;$('observations').hidden=true;};
$<HTMLInputElement>('scrub').oninput=e=>{playing=false;state.time=Number((e.target as HTMLInputElement).value);world.time=state.time;details();};
document.querySelectorAll<HTMLButtonElement>('[data-speed]').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.speed);document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));});
function compare(){if(busy)return;playing=false;state.time=END;world.time=END;compared=true;const better=result.journeys.slice(0,3).map((j,i)=>({j,b:baseline.journeys[i],delta:j.arrival===null||baseline.journeys[i].arrival===null?0:baseline.journeys[i].arrival!-j.arrival}));const win=[...better].sort((a,b)=>b.delta-a.delta)[0],loss=[...better].sort((a,b)=>a.delta-b.delta)[0];
 const cards:string[]=[];if(win.delta>1)cards.push(`<button data-observe="${win.j.person.id}"><span><strong>${win.j.person.name} kommt früher an.</strong><span>${seconds(win.delta)} weniger unterwegs als im Ausgangsmorgen.</span></span></button>`);if(loss.delta< -1)cards.push(`<button data-observe="${loss.j.person.id}"><span><strong>${loss.j.person.name} braucht länger.</strong><span>${seconds(-loss.delta)} zusätzlich. Prüfe die Autozufahrt.</span></span></button>`);if(result.visits>baseline.visits)cards.push(`<button data-observe="park"><span><strong>Dein Ort wird benutzt.</strong><span>${result.visits} berechnete Besuche mit Hin- und Rückweg.</span></span></button>`);if(!cards.length)cards.push('<div><strong>Was könnte den Morgen verändern?</strong><span>Untersuche Maras Umweg oder verbinde den Eingang deines Grünorts.</span></div>');
 $('observations').innerHTML=`<div class="observation-head"><div><span class="eyebrow">DENSELBEN MORGEN VERGLEICHEN</span><h2>Was deine Idee bewirkt.</h2></div><button id="close-observations" aria-label="Vergleich schließen">Schließen</button></div><div class="observation-cards">${cards.slice(0,3).join('')}</div><p class="comparison-summary">Pünktlich: ${baseline.onTime} → ${result.onTime} von ${state.count} · Nicht erreichbar: ${result.unreachable} · Besuche: ${result.visits}</p>`;$('observations').hidden=false;$('close-observations').onclick=()=>$('observations').hidden=true;
 $('observations').querySelectorAll<HTMLButtonElement>('[data-observe]').forEach(button=>button.onclick=()=>{const park=button.dataset.observe==='park';const id=park?1:Number(button.dataset.observe);select(id);const j=result.journeys[id];state.time=park?(j.segments.find(s=>s.kind==='stay')?.start||j.person.breakStart)+15:Math.max(j.person.depart,(j.arrival||j.person.depart)-40);world.time=state.time;world.focus(park?'park':j.person.goal);$('observations').hidden=true;details();});controls();details();}
$('compare').onclick=compare;
$('accept').onclick=async()=>{if(busy||!compared)return;state=commit(state);await refresh(true);toast('Dein Viertel ist übernommen. Es ist jetzt der neue Ausgangsmorgen.');};
const KEY='minterra.save.v1';
$('save').onclick=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));toast('Spielstand in diesem Browser gespeichert.');}catch{toast('Speichern ist blockiert. Über „Spielstand“ kannst du eine Datei exportieren.');}};
function dialog(html:string){$('dialog-content').innerHTML=html;$<HTMLDialogElement>('dialog').showModal();}
$('close-dialog').onclick=()=>$<HTMLDialogElement>('dialog').close();
$('help').onclick=()=>dialog(`<div class="eyebrow">WILLKOMMEN IM VIERTEL</div><h2>Folge deiner nächsten Idee.</h2><ol><li>Wähle Mara und sieh ihren Schulweg an. Grün zeigt deinen Entwurf, Sand den Ausgangsmorgen.</li><li>Öffne einen einzelnen Anschluss unter <b>Verbinden</b>. Wege lassen sich kombinieren.</li><li>Starte denselben Morgen. 1× entspricht einer Spielsekunde pro realer Sekunde; 20× beschleunigt ihn.</li><li>Vergleiche die Folgen für Mara, Cem und Ruth. Übernehmen macht deinen Entwurf zum neuen Ausgangszustand.</li><li>Gestalte einen Garten oder Platz. Cem braucht einen angeschlossenen Eingang und genügend Zeit für Hinweg, Pause und Rückweg.</li></ol><p>Du darfst jederzeit frei bauen. Leertaste pausiert, Escape schließt Dialoge. Das Viertel ist erfunden; reale Ehrenfeld-Geometrie folgt in einer späteren Stufe.</p>`);
$('data').onclick=()=>{dialog(`<h2>Dein Spielstand</h2><p>Nur bei „Speichern“ wird dein Spielstand lokal in diesem Browser abgelegt. Keine Konten und keine Übertragung deines Spielstands. Für Seitenabrufe gelten die zentralen Datenschutzhinweise. Ein Datei-Export sichert deinen Stand unabhängig vom Browser.</p><div class="data-actions"><button id="export-save">Datei exportieren</button><label class="file-label">Datei laden<input id="import-save" type="file" accept="application/json,.json"></label><button id="load-save">Gespeicherten Stand laden</button><button id="delete-save">Browserspeicher löschen</button><button id="new-game">Neues Testviertel</button></div><p id="data-message" role="status"></p>`);
 $('export-save').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='MINTERRA-Spielstand.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const load=async(raw:string)=>{try{const next=parseSave(raw);state=next;await refresh(true);select(state.selected);$<HTMLDialogElement>('dialog').close();toast('Spielstand geladen.');}catch(e){$('data-message').textContent=(e as Error).message;}};
 $('load-save').onclick=()=>{try{const raw=localStorage.getItem(KEY);raw?void load(raw):$('data-message').textContent='Noch kein gespeicherter Stand.';}catch{$('data-message').textContent='Browserspeicher nicht zugänglich.';}};
 $<HTMLInputElement>('import-save').onchange=async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(f.size>100000){$('data-message').textContent='Die Spielstanddatei ist zu groß.';return;}await load(await f.text());};
 $('delete-save').onclick=()=>{try{localStorage.removeItem(KEY);$('data-message').textContent='Gespeicherte Browserkopie gelöscht. Die laufende Sitzung bleibt erhalten.';}catch{$('data-message').textContent='Browserspeicher nicht zugänglich.';}};
 $('new-game').onclick=()=>{dialog('<h2>Neues Testviertel?</h2><p>Die laufende Sitzung wird ersetzt. Eine bereits gespeicherte Browserkopie bleibt erhalten.</p><button id="confirm-new">Neu beginnen</button>');$('confirm-new').onclick=async()=>{state=fresh();await refresh(true);select(0);$<HTMLDialogElement>('dialog').close();};};};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes((e.target as HTMLElement).tagName)&&!$<HTMLDialogElement>('dialog').open){e.preventDefault();$('play').click();}});
let previous=performance.now(),lastDetail=0;
function tick(now:number){const dt=Math.min((now-previous)/1000,.1);previous=now;if(playing&&!busy&&!document.hidden&&!$<HTMLDialogElement>('dialog').open){state.time=Math.min(END,state.time+dt*speed);if(state.time===END){playing=false;compare();}}world.time=state.time;if($('clock').textContent!==clock(state.time))$('clock').textContent=clock(state.time);$<HTMLInputElement>('scrub').value=String(state.time);if($('play').dataset.playing!==String(playing)){$('play').dataset.playing=String(playing);$('play').innerHTML=icon(playing?'pause':'play');$('play').setAttribute('aria-label',playing?'Pause':'Morgen abspielen');}if(now-lastDetail>700){details();lastDetail=now;}requestAnimationFrame(tick);}
refresh(true).then(()=>{requestAnimationFrame(tick);toast('Wähle Mara. Welchen Weg würdest du ihr öffnen?');}).catch(e=>{$('loading').hidden=false;$('loading').textContent='Start fehlgeschlagen: '+String(e);});
// Read-only evidence for local QA. No hidden mutation API.
Object.defineProperty(window,'minterraStatus',{get:()=>({ready:!busy,state:structuredClone(state),result:result?{onTime:result.onTime,visits:result.visits,computeMs:result.computeMs}:null,fps:world.engine.getFps()})});
